setup.ilm.enabled: false
setup.template.name: "log-dat"
setup.template.pattern: "log-dat*"

filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /logs/*.log
  json.keys_under_root: true

processors:
  - decode_json_fields:
      fields: ["level", "ts", "caller", "msg", "diagnostics", "requestInfo"]

output.elasticsearch:
  hosts: ["${ZINCSEARCH_INSTANCE_IP}"]
  path: "/es/"
  index: "log-datBoyo"
  username: "admin"
  password: "${ZINCSEARCH_PASS}"